using System;
using System.ComponentModel.DataAnnotations;
using SampleAPI.DTO;

namespace SampleAPI.Models
{
    /// <summary>
    /// Stores dimensional information regarding a location
    /// </summary>
    public class LocationDimension : BaseSingleRecordModel
    {
        #region Properties

        /// <summary>
        /// The guid based location identifier generated by LDM
        /// </summary>
        [Required]
        public Guid LocationID { get; set; }

        /// <summary>
        /// The integer based friendly location identifier generated by LDM
        /// </summary>
        [Required]
        public int LocationNumber { get; set; }

        #endregion 

        #region Constructors
        /// <summary>
        /// Create a new instance of the LocationDimension object
        /// </summary>
        /// <param name="lctnId"></param>
        /// <param name="locationID"></param>
        /// <param name="locationNumber"></param>
        public LocationDimension(int lctnId, Guid locationID, int locationNumber)
        {
            ID = lctnId;
            LocationID = locationID;
            LocationNumber = locationNumber;
        }

        /// <summary>
        /// Create a new instance of the the LocationDimension object
        /// </summary>
        /// <param name="locationID"></param>
        /// <param name="locationNumber"></param>
        public LocationDimension(Guid locationID, int locationNumber)
        {
            LocationID = locationID;
            LocationNumber = locationNumber;
        }

        /// <summary>
        /// Create a new instance of an empty LocationDimension object
        /// </summary>
        public LocationDimension()
        {

        }

        #endregion

        #region Conversions
        /// <summary>
        /// Casts LocationDTO to LocationDimension
        /// </summary>
        /// <param name="a"></param>
        public static explicit operator LocationDimension(LocationDTO a)
        {
            LocationDimension ad = new LocationDimension();
            ad.ID = a.ID;
            ad.LocationID = a.LocationID;
            ad.LocationNumber = a.LocationNumber;

            return ad;
        }

        /// <summary>
        /// Returns the corresponding DTO object
        /// </summary>
        /// <returns></returns>
        public LocationDTO GetDTO()
        {
            LocationDTO ad = new LocationDTO();
            ad.LocationID = LocationID;
            ad.LocationNumber = LocationNumber;
            ad.ID = ID;

            return ad;
        }

        #endregion 
    }
}