using System;

namespace SampleAPI.DTO
{
    /// <summary>
    /// Location Data Transfer Object
    /// </summary>
    public class LocationDTO : BaseDTO
    {
        #region Properties

        /// <summary>
        /// The guid based location identifier generated by LDM
        /// </summary>
        public Guid LocationID { get; set; }

        /// <summary>
        /// The integer based friendly location identifier generated by LDM
        /// </summary>
        public int LocationNumber { get; set; }

        #endregion
    }
}